
# ------------------------------------------------------------
# Networking Settings
# ------------------------------------------------------------

variable "aws_region" {
  type        = string
  description = "The AWS region for the provider to deploy resources into."
  default     = "us-east-1"
}

variable "vpc_cidr_block" {
  type        = string
  description = "CIDR block of the VPC to create."
  default     = "10.0.0.0/16"
}

variable "dev1_subnet_az" {
  type        = string
  description = "Availability Zone of the subnet 1."
  default     = "us-east-1a"
}

variable "dev2_subnet_az" {
  type        = string
  description = "Availability zone of subnet 2."
  default     = "us-east-1b"
}

variable "dev1_subnet_cidr_block" {
  type        = string
  description = "CIDR block of subnet 1 to create."
  default     = "10.0.1.0/24"
}

variable "dev2_subnet_cidr_block" {
  type        = string
  description = "CIDR block of subnet 1 to create."
  default     = "10.0.2.0/24"
}

variable "dev1_subnet_nic_private_ip" {
  type        = list(string)
  description = "CIDR block of subnet 1 to create."
  default     = ["10.0.1.50"]
}

variable "ingress_cidr_blocks" {
  type    = list(string)
  default = ["0.0.0.0/00.0.0.0/0"]
} 

# ------------------------------------------------------------
# Key Pair Settings
# ------------------------------------------------------------


variable "key_name" {
  type        = string
  default     = "splunk-key-pair"
  description = "Key-pair generated by Terraform"
}

# ------------------------------------------------------------
# EC2 Settings
# ------------------------------------------------------------

variable "ubuntu-ami" {
  type = string
  default = "ami-0ee23bfc74a881de5"
  description = "us-east-1	bionic	18.04	amd64	hvm-ssd	20220901"
}

variable "instance_type" {
  type = string
  default = "t2.micro"
}

# ------------------------------------------------------------
# Splunk Settings
# ------------------------------------------------------------


